<?php declare(strict_types=1);
if (!defined('B_PROLOG_INCLUDED')||B_PROLOG_INCLUDED!==true) die();
$content=\Bitrix\Main\DI\ServiceLocator::getInstance()->get(\Bxmax\Booking\Service\CatalogService::class)->content();
$services=$content['SERVICES']; $masters=$content['MASTERS'];
$asset='/local/modules/bxmax.booking/assets';
$h=static fn($s):string=>htmlspecialcharsbx((string)$s);
$price=static fn($p):string=>number_format((float)$p,0,',',' ');
?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Лак&Точка — студия маникюра в Саратове</title><meta name="description" content="Маникюр, педикюр и немного времени для себя. Выберите мастера и свободное время — запись в Лак&Точка онлайн."><meta name="theme-color" content="#ffffff"><link rel="stylesheet" href="<?=$asset?>/fonts.css"><link rel="stylesheet" href="<?=$asset?>/landing.css?v=<?=filemtime(dirname(__DIR__).'/assets/landing.css')?>"><link rel="icon" href="<?=$asset?>/favicon.svg" type="image/svg+xml"><script src="<?=$asset?>/landing.js?v=<?=filemtime(dirname(__DIR__).'/assets/landing.js')?>" defer></script></head>
<body><a class="skip" href="#booking">Перейти к записи</a>
<header class="header" id="top"><a class="small-brand" href="#top" aria-label="Лак и Точка — наверх">л&т<span>САРАТОВ</span></a><nav class="top-nav" aria-label="Главная навигация"><a href="#services">МАНИКЮР</a><a href="#price">ПЕДИКЮР</a><a href="#about">О СТУДИИ</a></nav><a class="header-cta" href="#booking">ЗАПИСАТЬСЯ <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="Открыть меню"><span></span><span></span></button><nav id="mobile-menu" class="mobile-menu" aria-label="Мобильная навигация" hidden><a href="#services">Услуги</a><a href="#gallery">Работы</a><a href="#masters">Мастера</a><a href="#booking">Записаться</a><a href="#contacts">Контакты</a></nav></header>
<main>
<section class="hero" aria-labelledby="hero-title"><h1 id="hero-title">ЛАК<span>&</span>ТОЧКА</h1><p class="hero-subtitle">СТУДИЯ МАНИКЮРА</p><div class="hero-collage"><img class="hero-main" src="<?=$asset?>/images/hero.jpg" alt="Ухоженные руки с лаконичным маникюром и тонким кольцом" fetchpriority="high" width="760" height="920"><img class="hero-left" src="<?=$asset?>/images/work-1.jpg" alt="Глубокий тёмный оттенок на аккуратных ногтях" width="420" height="570"><img class="hero-right" src="<?=$asset?>/images/work-2.jpg" alt="Мастер бережно наносит покрытие" width="400" height="520"><img class="hero-far" src="<?=$asset?>/images/work-3.jpg" alt="Бережный уход за руками" width="220" height="300"><div class="hero-note"><span class="eyebrow">КРАСИВО. БЕРЕЖНО. ВАШЕ.</span><p>Маникюр, который<br>хочется рассматривать.</p><a href="#booking" class="text-link">Записаться <span aria-hidden="true">↗</span></a></div><nav class="hero-nav" aria-label="Разделы страницы"><a href="#about">О СТУДИИ</a><a href="#services">УСЛУГИ</a><a href="#gallery">РАБОТЫ</a><a href="#masters">МАСТЕРА</a><a href="#contacts">КОНТАКТЫ</a></nav></div><div class="hero-bottom"><span>ЕЖЕДНЕВНО · 10:00–20:00</span><a href="#about">ВРЕМЯ ДЛЯ СЕБЯ <span aria-hidden="true">↓</span></a></div></section>
<section class="offer section reveal"><p class="eyebrow">МАЛЕНЬКИЙ РИТУАЛ</p><h2>КРАСИВЫЕ РУКИ.<br>И НИЧЕГО ЛИШНЕГО.</h2><p class="script">Только вы</p><p class="intro">Час без спешки, любимый цвет и забота в деталях.<br>Выберите время — мы будем ждать.</p><a class="button" href="#booking">Записаться <span aria-hidden="true">↗</span></a></section>
<section id="about" class="section about reveal"><p class="eyebrow">О СТУДИИ</p><h2>БОЛЬШЕ, ЧЕМ МАНИКЮР</h2><p class="intro">«Лак&Точка» — небольшая студия, где вас помнят по имени.<br>Можно поговорить, можно помолчать. Мы позаботимся о руках,<br>а вы просто побудете в моменте.</p><div class="advantages"><article><span class="line-icon" aria-hidden="true">✧</span><h3>БЕРЕЖНО</h3><p>Подбираем технику<br>под ваши ногти</p></article><article><span class="line-icon" aria-hidden="true">◇</span><h3>ЧИСТО</h3><p>Стерильные инструменты<br>вскрываем при вас</p></article><article><span class="line-icon" aria-hidden="true">◷</span><h3>ВОВРЕМЯ</h3><p>Ваш час в расписании<br>принадлежит только вам</p></article><article><span class="line-icon" aria-hidden="true">♡</span><h3>ПО-ВАШЕМУ</h3><p>От прозрачного нюда<br>до смелого цвета</p></article></div></section>
<section id="services" class="section featured"><div class="reveal section-title"><p class="eyebrow">НАШИ РИТУАЛЫ</p><h2>В ДЕТАЛЯХ —<br>ВСЯ КРАСОТА</h2></div><?php $photos=['hero','work-2','work-1','work-3']; foreach(array_slice($services,0,4) as $i=>$s): ?><article class="feature reveal"><div class="photo-frame"><img src="<?=$asset?>/images/<?=$photos[$i]?>.jpg" alt="<?=$h($s['NAME'])?> — пример ухода за руками" loading="lazy" width="660" height="760"></div><div class="feature-copy"><p class="eyebrow">РИТУАЛ № <?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></p><h3><?=$h($s['NAME'])?></h3><p><?=$h($s['PREVIEW_TEXT'])?></p><p class="feature-price"><span>стоимость:</span> <?=$price($s['PRICE_VALUE'])?> <small>₽</small></p><a class="button" href="#booking" data-service="<?=(int)$s['ID']?>">Записаться <span aria-hidden="true">↗</span></a></div></article><?php endforeach; ?></section>
<section id="price" class="section price-section reveal"><p class="eyebrow">ПРОЗРАЧНО И ПРОСТО</p><h2>УСЛУГИ И СТОИМОСТЬ</h2><p class="intro">Все цены — за полный ритуал. Без неожиданных дополнений.</p><div class="price-list"><?php foreach($services as $s): ?><a href="#booking" data-service="<?=(int)$s['ID']?>" class="price-row"><span><?=$h($s['NAME'])?><small><?=$h($s['PREVIEW_TEXT'])?></small></span><strong><?=$price($s['PRICE_VALUE'])?> ₽ <span aria-hidden="true">↗</span></strong></a><?php endforeach; ?></div><p class="fine">Для каждой услуги зарезервирован час. Если нужен сложный дизайн — обсудим его до визита.</p></section>
<section class="offer section reveal"><p class="eyebrow">В ВАШЕМ РИТМЕ</p><h2>НАЙДИТЕ ВРЕМЯ<br>ДЛЯ СЕБЯ</h2><p class="script">Вы заслужили</p><a class="button" href="#booking">Выбрать время <span aria-hidden="true">↗</span></a></section>
<section id="gallery" class="section gallery reveal"><p class="eyebrow">ВДОХНОВЕНИЕ</p><h2>КРАСОТА В КАЖДОМ ЖЕСТЕ</h2><p class="intro">Тихие оттенки, чистые линии и цвет под настроение.</p><div class="gallery-grid" id="gallery-track"><figure><img src="<?=$asset?>/images/hero.jpg" alt="Нежный естественный маникюр на руках с кольцом" loading="lazy" width="680" height="700"><figcaption>01 / Естественность</figcaption></figure><figure><img src="<?=$asset?>/images/work-1.jpg" alt="Выразительное тёмное покрытие ногтей" loading="lazy" width="680" height="700"><figcaption>02 / Глубина цвета</figcaption></figure><figure><img src="<?=$asset?>/images/work-2.jpg" alt="Аккуратное нанесение лака кистью" loading="lazy" width="680" height="700"><figcaption>03 / Внимание к деталям</figcaption></figure><figure><img src="<?=$asset?>/images/work-4.jpg" alt="Пастельный маникюр крупным планом" loading="lazy" width="680" height="700"><figcaption>04 / Нежный акцент</figcaption></figure></div><div class="gallery-controls"><button type="button" data-gallery="-1" aria-label="Предыдущие фотографии">←</button><span id="gallery-count" role="status">01 / 02</span><button type="button" data-gallery="1" aria-label="Следующие фотографии">→</button></div><p class="fine">Стоковые примеры стиля и процесса. Реальные работы студии появятся здесь после открытия.</p></section>
<section id="masters" class="section masters"><div class="reveal"><p class="eyebrow">В ХОРОШИХ РУКАХ</p><h2>ВАШИ МАСТЕРА</h2><p class="script">Знакомьтесь</p></div><div class="master-grid"><?php foreach($masters as $m): ?><article class="master reveal"><div class="photo-frame"><img src="<?=$h($m['PHOTO_VALUE'])?>" alt="<?=$h($m['NAME'])?> — мастер студии, иллюстративный портрет" loading="lazy" width="500" height="650"></div><p class="eyebrow"><?=$h($m['SPECIALTY_VALUE'])?></p><h3><?=$h($m['NAME'])?></h3><p><?=$h($m['PREVIEW_TEXT'])?></p><a class="text-link" href="#booking" data-master="<?=(int)$m['ID']?>">Записаться к мастеру <span aria-hidden="true">↗</span></a></article><?php endforeach; ?></div></section>
<section id="reviews" class="section reviews reveal"><p class="eyebrow">ТЁПЛЫЕ СЛОВА</p><h2>ЗА ЧТО НАС ВЫБИРАЮТ</h2><p class="script">Спасибо</p><p class="fine">Примеры отзывов для демонстрационной студии</p><div class="review-list"><?php foreach([
 ['Ирина','Маникюр с гель-лаком','Попросила сделать тонкое покрытие — без привычного объёма. Анна поняла с полуслова. Смотрю на руки весь день.'],
 ['Ольга','Педикюр','Для меня главное — чтобы аккуратно и без спешки. Мария всё объяснила, показала инструменты. Очень спокойный час получился.'],
 ['Алина','Маникюр с френчем','Обычно долго выбираю цвет. Здесь предложили три оттенка под мою кожу, и один оказался прямо моим. Маленькая деталь, а приятно.'],
 ['Наталья','Японский маникюр','Пришла отдохнуть от покрытия. Ушла с гладкими блестящими ногтями и ощущением, что наконец сделала что-то для себя.'],
 ] as $i=>$review): ?><details <?=$i===0?'open':''?>><summary><span><?=$h($review[0])?><small><?=$h($review[1])?></small></span><span class="review-stars" aria-label="5 из 5">★★★★★</span><span class="plus" aria-hidden="true">+</span></summary><p>«<?=$h($review[2])?>»</p></details><?php endforeach; ?></div></section>
<?php $APPLICATION->IncludeComponent('bxmax:booking','',[],false,['HIDE_ICONS'=>'Y']); ?>
<section id="contacts" class="section contacts reveal"><div><p class="eyebrow">КОНТАКТЫ</p><h2>ЧТОБЫ БЫТЬ<br><span>БЛИЖЕ</span></h2><p class="script">Ждём вас</p></div><div class="contact-grid"><div><p class="eyebrow">АДРЕС</p><p>Саратов, ул. Вольская, 58</p><p class="fine">Вход со двора, первый этаж<br>Демонстрационный адрес студии</p></div><div><p class="eyebrow">ЧАСЫ РАБОТЫ</p><p>Каждый день<br>с 10:00 до 20:00</p></div><div><p class="eyebrow">ДО ВСТРЕЧИ</p><p><a href="tel:+78452000000">+7 (8452) 00-00-00</a></p><p class="fine">Демонстрационный телефон</p><a class="text-link" href="#booking">Онлайн-запись ↗</a></div></div><div class="location-card"><span class="location-word">САРАТОВ</span><span class="location-pin" aria-hidden="true">✦</span><p>ЛАК&ТОЧКА · ВОЛЬСКАЯ, 58</p><span>Место, где можно выдохнуть.</span></div></section>
</main><footer><span>© <?=date('Y')?> ЛАК&ТОЧКА</span><button class="plain-button" data-policy>Обработка персональных данных</button><a href="#top">НАВЕРХ ↑</a></footer>
<dialog id="privacy" aria-labelledby="privacy-title"><button class="dialog-close" aria-label="Закрыть" data-close>×</button><p class="eyebrow">ЛАК&ТОЧКА</p><h2 id="privacy-title">Обработка данных</h2><p>Нажимая отметку согласия, вы разрешаете студии «Лак&Точка» использовать ваше имя, телефон и детали выбранного визита для оформления записи и связи по ней. Время согласия сохраняется вместе с заявкой. Рекламные рассылки не предусмотрены.</p><p>Доступ к заявке есть только у сотрудников с соответствующими правами. Чтобы отозвать согласие или удалить запись, обратитесь к администратору студии. При удалении заявки её данные удаляются из списка, а время освобождается.</p><p>Это демонстрационный стенд: используйте тестовые данные. Перед запуском реальной студии необходимо указать реквизиты оператора, способ связи и утвердить срок хранения данных.</p><button class="button" data-close>Понятно</button></dialog><a class="back-top" href="#top" aria-label="Вернуться наверх">↑</a></body></html>
