CREATE TABLE IF NOT EXISTS bxmax_booking_slot (
	ID INT NOT NULL AUTO_INCREMENT,
	MASTER_ID INT NOT NULL,
	STARTS_AT DATETIME NOT NULL,
	ENDS_AT DATETIME NOT NULL,
	CLOSED CHAR(1) NOT NULL DEFAULT 'N',
	CREATED_AT DATETIME NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY ux_bxmax_booking_slot_master_start (MASTER_ID, STARTS_AT),
	KEY ix_bxmax_booking_slot_starts_at (STARTS_AT)
);

CREATE TABLE IF NOT EXISTS bxmax_booking_entry (
	ID INT NOT NULL AUTO_INCREMENT,
	SLOT_ID INT NOT NULL,
	MASTER_ID INT NOT NULL,
	SERVICE_ID INT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PHONE VARCHAR(32) NOT NULL,
	CONSENT_AT DATETIME NOT NULL,
	CREATED_AT DATETIME NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY ux_bxmax_booking_entry_slot (SLOT_ID),
	KEY ix_bxmax_booking_entry_master (MASTER_ID),
	KEY ix_bxmax_booking_entry_service (SERVICE_ID)
);
