<?php declare(strict_types=1);
if (!defined('B_PROLOG_INCLUDED')||B_PROLOG_INCLUDED!==true) die();
$h=static fn($s):string=>htmlspecialcharsbx((string)$s);
$today=new \DateTimeImmutable('today',new \DateTimeZone('Europe/Saratov'));
?>
<section id="booking" class="section booking reveal" aria-labelledby="booking-title"><p class="eyebrow">ВАШ ЧАС ЗАБОТЫ</p><h2 id="booking-title">ЗАПИШЕМ ВАС?</h2><p class="script">До встречи</p><p class="intro">Выберите мастера и время. Запись подтвердится сразу.</p>
<form id="booking-form" data-today="<?=$today->format('Y-m-d')?>" data-sessid="<?=bitrix_sessid()?>" novalidate>
<div class="booking-step"><span class="step-number">01</span><h3>Выберите свой ритуал</h3></div><div class="form-pair"><div><label for="booking-service">Услуга</label><select id="booking-service" name="serviceId" required><?php foreach($arResult['SERVICES'] as $s): ?><option value="<?=(int)$s['ID']?>"><?=$h($s['NAME'])?> · <?=number_format((float)$s['PRICE_VALUE'],0,',',' ')?> ₽</option><?php endforeach; ?></select></div><div><label for="booking-master">Мастер</label><select id="booking-master" name="masterId" required><?php foreach($arResult['MASTERS'] as $m): ?><option value="<?=(int)$m['ID']?>"><?=$h($m['NAME'])?></option><?php endforeach; ?></select></div></div>
<div class="booking-step"><span class="step-number">02</span><h3>Найдите удобное время</h3></div><p class="fine">Время студии: Саратов, UTC+4. Все ритуалы — 60 минут.</p><div class="week-nav"><button type="button" id="week-prev" aria-label="Предыдущая неделя">←</button><span id="week-label"></span><button type="button" id="week-next" aria-label="Следующая неделя">→</button></div><div id="booking-days" role="tablist" aria-label="Выберите день"></div><div id="slot-panel" role="tabpanel" aria-label="Время выбранного дня"><p id="day-label" class="day-label"></p><div id="booking-slots" role="listbox" aria-label="Свободное время" aria-describedby="slot-help" aria-busy="true"></div></div><p id="slot-help" class="fine">Зачёркнутое время уже занято. Стрелки — выбор времени, Enter — подтвердить.</p><p id="slots-status" role="status" aria-live="polite"></p><p id="selection-status" role="status" aria-live="polite">Время ещё не выбрано</p>
<div class="booking-step"><span class="step-number">03</span><h3>Как к вам обращаться?</h3></div><div class="form-pair"><div><label for="booking-name">Ваше имя</label><input id="booking-name" name="name" autocomplete="given-name" placeholder="Например, Анна" minlength="2" maxlength="100" required aria-describedby="form-status"></div><div><label for="booking-phone">Телефон</label><input id="booking-phone" type="tel" name="phone" autocomplete="tel" inputmode="tel" placeholder="+7 (___) ___-__-__" maxlength="30" required aria-describedby="form-status"></div></div>
<div class="consent"><input type="checkbox" id="booking-consent" name="consent" value="1" required><label for="booking-consent">Я согласен(на) на обработку персональных данных для оформления записи.</label></div><button type="button" class="policy-link" data-policy>Прочитать условия обработки данных</button><p id="form-status" role="status" aria-live="polite" tabindex="-1"></p><div class="submit-row"><button class="button" type="submit" id="booking-submit">Подтвердить запись <span aria-hidden="true">↗</span></button><span class="fine">Без звонков и ожидания.<br>Только ваше время.</span></div></form>
<div id="booking-success" hidden role="status" aria-live="polite" tabindex="-1"><span class="success-mark" aria-hidden="true">✓</span><h3>Вы записаны!</h3><p id="success-detail"></p><p>Будем ждать вас в «Лак&Точка».<br>Саратов, ул. Вольская, 58.</p><button type="button" class="button" id="booking-again">Записаться ещё</button></div><noscript><p>Для онлайн-записи включите JavaScript в браузере.</p></noscript></section>
